export const ALLSUBCATEGORIES = "ALLSUBCATEGORIES"
export const ALLCOLORS = "ALLCOLORS"
export const ALLBRANDS = "ALLBRANDS"
export const ALLSIZES = "ALLSISEZ"
export const ALLCATEGORIES = "ALLCATEGORIES"
export const ALLPRODUCTS = "ALLPRODUCTS"
export const SELECTEDCATEGORY = "SELECTEDCATEGORY"
export const CLEAN_DETAIL = 'CLEAN_DETAIL'
export const PRODUCTS_DETAIL = 'PRODUCTS_DETAIL'
export const PRODUCTS_FILTERED = 'PRODUCTS_FILTERED'
export const POST_FAVORITES_API = 'POST_FAVORITES_API'
export const POST_FAVORITES_API_INICIO = 'POST_FAVORITES_API_INICIO'
export const POST_FAVORITES_LS = 'POST_FAVORITE_LS'
export const DELETE_FAVORITES = 'DELETE_FAVORITES'
export const DELETE_FAVORITES_API = 'DELETE_FAVORITES_API'
export const ADD_TOCART = 'ADD_TOCART'
export const PRODUCTOS = 'PRODUCTOS'

//provisional
export const COPY_ALLPRODUCTS = 'COPY_ALLPRODUCTS'